apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-75000
spec:
  template:
    metadata:
      labels:
        app: consumer-75000
    spec:
      imagePullSecrets:
        - name: ibm-entitlement-key
      containers:
        - name: kafka-perf
          image: cp.icr.io/cp/ibm-eventstreams-kafka:11.5.0
          command:
            - "/opt/kafka/bin/kafka-consumer-perf-test.sh"
            - "--topic"
            - "QUOTA.CONSUME.75000"
            - "--messages"
            - "5000000"
            - "--group"
            - "eem-quotas-test"
            - "--consumer.config"
            - "/config/consumer.properties"
            - "--timeout"
            - "120000"
            - "--bootstrap-server"
            - "my-eem-gateway-ibm-egw-rt-1-event-automation.apps.dale-lane.cp.fyre.ibm.com:443"
          volumeMounts:
            - mountPath: /certs/cluster
              name: gateway-ca
              readOnly: true
            - mountPath: /config
              name: consumer-properties
              readOnly: true
      volumes:
        - name: gateway-ca
          secret:
            items:
            - key: eem-ca.pem
              path: eem-ca.pem
            secretName: eem-ca-cert
        - name: consumer-properties
          configMap:
            name: quotas-consume-75000
      restartPolicy: Never
  backoffLimit: 1
  completions: 1
  parallelism: 1
